-- Inserts our pages into the table. Should be run after a drop tables (i.e. basic.sql) to avoid duplicate entries,
    -- although I've built in some resistance to that in the SQL statements under /ajax
-- Do NOT add a / to home. It should be kept blank. All other ones will start with a / but not end in one.
    -- Go by the examples already here

-- Last updated 12/11 8:36 AM by Zach Butler

INSERT INTO pages (name, path) VALUES
                    ('Home', ''),
                    ('Africa', '/africa'),
                    ('Akiba Market', '/akiba-market'),
                    ('Dino World', '/dino-world'),
                    ('Honey Bee', '/honey-bee'),
                    ('Junction Plaza', '/junction-plaza'),
                    ('Parking', '/parking'),
                    ('North America', '/north-america'),
                    ('Bison', '/north-america/bison'),
                    ('Black Bear', '/north-america/black-bear'),
                    ('Cypress Swamp', '/north-america/cypress-swamp'),
                    ('Elk', '/north-america/elk'),
                    ('Garden Friends Playground', '/north-america/garden-friends-playground'),
                    ('Marsh', '/north-america/marsh'),
                    ('Rocky Coast', '/north-america/rocky-coast'),
                    ('Streamside', '/north-america/streamside'),
                    ('Tyrannosaurus Rex', '/dino-world/tyrannosaurus-rex'),
                    ('Apatosaurus', '/dino-world/apatosaurus'),
                    ('Triceratops', '/dino-world/triceratops'),
                    ('Stegosaurus', '/dino-world/stegosaurus'),
                    ('Parasaurolophus', '/dino-world/parasaurolophus'),
                    ('Allosaurus', '/dino-world/allosaurus'),
                    ('Diabloceratops', '/dino-world/diabloceratops'),
                    ('Muttaburrasaurus', '/dino-world/muttaburrasaurus'),
                    ('Megalosaurus', '/dino-world/megalosaurus'),
                    ('Deinonychus', '/dino-world/deinonychus'),
                    ('Iguanodon', '/dino-world/iguanodon'),
                    ('Cryolophosaurus', '/dino-world/cryolophosaurus'),
                    ('Suchomimus', '/dino-world/suchomimus'),
                    ('Brachiosaurus', '/dino-world/brachiosaurus'),
                    ('Dilophosaurus', '/dino-world/dilophosaurus'),
                    ('Pachyrhinosaurus', '/dino-world/pachyrhinosaurus'),
                    ('Chimpanzee', '/africa/chimpanzee'),
                    ('Elephant', '/africa/elephant'),
                    ('Gorilla Baboon', '/africa/gorilla-baboon'),
                    ('Lemur', '/africa/lemur'),
                    ('Lion', '/africa/lion'),
                    ('Ostrich Antelope', '/africa/ostrich-antelope'),
                    ('Red River Hog', '/africa/red-river-hog'),
                    ('Rhinoceros', '/africa/rhinoceros'),
                    ('Zebra Ostrich Giraffe', '/africa/zebra-ostrich-giraffe'),
                    ('Types of Bees', '/honey-bee/types'),
                    ('Colony Collapse', '/honey-bee/colony-collapse'),
                    ('Honey Bee Gift Shop', '/honey-bee/gift-shop'),
                    ('NC Beekeepers Assoc', '/honey-bee/nc-assoc'),
                    ('Bee Habitats', '/honey-bee/habitats'),
                    ('Carousel', '/junction-plaza/carousel'),
                    ('Continental Cool Treats', '/junction-plaza/continental-cool-treats'),
                    ('Continental Crossings Pizza', '/junction-plaza/continental-crossings-pizza'),
                    ('Junction Springs Cafe', '/junction-plaza/junction-springs-cafe'),
                    ('Junction Theatre', '/junction-plaza/junction-theatre'),
                    ('Junction Tram Stop', '/junction-plaza/junction-tram-stop'),
                    ('Kids Junction Gift Shop', '/junction-plaza/kids-junction-gift-shop'),
                    ('Kids Junction Gift Shop', '/junction-plaza/kids-junction-gift-shop'),
                    ('Amphitheater', '/akiba-market/amphitheater'),
                    ('Crocodile Café', '/akiba-market/crocodile-cafe'),
                    ('Hippo Beach', '/akiba-market/hippo-beach'),
                    ('Leopard Spot Gift Shop', '/akiba-market/leopard-spot-gift-shop'),
                    ('Oak Hill & Lakeside', '/akiba-market/oak-hill-lakeside'),
                    ('Picnic Areas', '/akiba-market/picnic-areas'),
                    ('Safari Gift Shop', '/akiba-market/safari-gift-shop'),
                    ('Ticket Booth', '/akiba-market/ticket-booth');



